### PR TITLE
Update README.md: Add TOC

### PR DESCRIPTION
**Pull request by 31KM**
f9a7a7d: 
Add TOC for better overview

3c46861: 
Add links
- LWN summary of the vulnerabilities
- LWN collection of postings about Meltdown/Spectre
- Chrome: Mitigation with Site Isolation

### CODE REVIEW

**Comment by marcan** [comment]
I assume this TOC is automatically generated. Can you manually trim it down to fewer levels? Something like:

```
 * [Common attack characteristics](#common-attack-characteristics)
 * [Attacks](#attacks)
   * [[MISPREDICT] Branch mis-prediction leaks subsequent data](#mispredict-branch-mis-prediction-leaks-subsequent-data)
   * [[BTI] Branch Target Injection](#bti-branch-target-injection)
   * [[PRIV-LOAD] Privileged data reads from unprivileged code](#priv-load-privileged-data-reads-from-+         
   * [[PRIV-REG] Privileged register reads from unprivileged code](#priv-reg-privileged-register-reads-from-unprivileged-code)
 * [Impacted CPU matrix](#impacted-cpu-matrix)
 * [PoCs](#pocs)
 * [Deployed or in-development mitigations](#deployed-or-in-development-mitigations)
 * [CPU Vendor response](#cpu-vendor-response)
 * [Software/Service Vendor response](#softwareservice-vendor-response) 
 * [Future Speculation](#future-speculation)
 * [References](#references)
```

**Comment by 31KM** [comment]
Sure, here you go :)
I included the sub levels of "Deployed or in-development mitigations" because I think the real world mitigations are quite important. If you don't like it I will trim them as well.

**Comment by marcan** [comment]
Breaking out the mitigations level is fine, but get rid of the top level and instead move the TOC to before the `Common attack characteristics` section. That way the intro is ahead of everything else and thee is no need for the top level of nesting. The top level is really more of a title than a section.

**Comment by 31KM** [comment]
Done

**Pull request merged**
